export const data = [
	{
		hasMore: true,
		RESULT_MSG: "성공",
		at: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJFWFRSQSI6Int9IiwiZXhwIjoxNzA1NDkyNDIzLCJpYXQiOjE3MDU0NzgwMjN9.4VBcUkb2_r99RVMkOr2LHIl6IR3HnEfo4BSnbC82YAY",
		DATA: [
			{
				TARGET: "RENTAL_HOUST",
				USER_IMAGE:
					"https://image.neoflat.net/MjNH00Hd4aJn9dRgPxWXKNtbEUs=/72x72/filters:no_upscale()/user/89278/bae52a84-7fa0-4e80-8fce-fdd8d94dc032",
				COMMENT_CNT: "0",
				ROWNUM: "466",
				REG_USER_TYPE: "10",
				OTHER_COMMENT_CNT: "0",
				LIKE_YN: "N",
				TYPE_NM: "#PICK",
				COMMENT_YN: "N",
				ID: "5058",
				WEIGHT: null,
				DISPLAY_TYPE: "01",
				RECEIPT_TO_DT: "2024-01-24 00:00:00.0",
				CONTENT_TEXT:
					"LH 한국토지주택공사에서 ‘수원 행복주택’ 입주자를 모집한다고 해요.\n \n해당 공고는 총 392호의 주택을 모집하며, 입주자격이 기존 행복주택 공고보다 완화되어 모집하는 공고인데요.\n \n또한, 이번 수원 행복주택 공고에 최종 당첨자 발표는 24년 5월10일로 예정되어 있다고 하니 이 점도 함께 확인해주세요!\n \n \n \n해당 공고는 입주자 모집공고일(24.01.12일) 현재 무주택자로서 다음 중 하나에 해당하는 사람이라면 신청이 가능해요.\n \n1️⃣ 대학생 계층\n2️⃣ 청년 계층\n소득 기준(전년도 도시근로자 가구원수별 가구당 월평균소득) 완화 조건 \n\n1순위 : 가구원수가 1인인 경우 120% 이하(1인 기준 : 4,024,661 원 이하)\n2순위 : 가구원수가 1인인 경우 140% 이하(1인 기준 : 4,695,438 원 이하)\n3순위 : 가구원수가 1인인 경우 150% 이하(1인 기준 : 5,030,826 원 이하)\n\n \n \n \n \nLH 수원 행복주택의 구체적인 신청일정은 아래와 같아요.\n \n \n \n이번 공고에 신청하고자 하는 사람이라면 인터넷 청약신청일(24.01.22~01.24일)에 ‘LH 청약플러스’ 홈페이지에 방문해 신청해야 해요.\n \n한 번만 신청해본다면 이후 나오는 공고들도 쉽게 신청할 수 있으니 아래 링크를 클릭해 신청방법을 확인해보세요!\n \n✅ LH 행복주택 신청방법 확인 &gt;\n \n \n여기까지 LH 한국토지주택공사에서 지원하는 수원 행복주택에 대해 알아보았는데요.\n \n이번 공고는 입주자격이 완화되어 기존 행복주택 소득 기준인 전년도 도시근로자 가구원수별 가구당 월평균소득의 100% 이하 (1인 : 4,024,661 원)가 아닌 최대 150%이하 (1인 : 5,030,826 원 이하)라면 신청이 가능하다고 하니 해당 공고가 올라왔을 때 꼭 한번 신청해보세요!\n \n추가로 궁금한 사항은 ’LH 청약플러스’ 홈페이지 또는 ‘LH 콜센터(📞1600-1004)’로 문의해주세요!\n \n\n",
				WEEKLY_TITLE_IMAGE2:
					"https://image.neoflat.net/zdi0Re9_snJ7ILIwjtvMWHDdUwo=/1376x220/filters:no_upscale()/community/5058/59d2253a-d78e-4ec8-b32c-5fe514afd6d8.jpg",
				BLIND_NOTI_CLUSTER_ID: null,
				VIEW_CNT: "10",
				NICKNAME: "알리미",
				TITLE_IMAGE4:
					"https://image.neoflat.net/ipk1aVU2DLLgNhxkskVXByMX0WY=/720x540/filters:no_upscale()/community/5058/59d2253a-d78e-4ec8-b32c-5fe514afd6d8.jpg",
				CATEGORY_CD: "C201",
				TAGS: "1인NEWS 1인가구지원정책 혼잘혜택",
				TARGET_STATUS: null,
				MOD_USER_TYPE: "10",
				AUTHOR_YN: "Y",
				TITLE_IMAGE3:
					"https://image.neoflat.net/YjYx7TVyg0BpAHsMZzENXRC23do=/720x328/filters:no_upscale()/community/5058/59d2253a-d78e-4ec8-b32c-5fe514afd6d8.jpg",
				TITLE_IMAGE2:
					"https://image.neoflat.net/RuLHomQxvoqjxxTgQIN9Fq9qvZM=/316x260/filters:no_upscale()/community/5058/59d2253a-d78e-4ec8-b32c-5fe514afd6d8.jpg",
				TAG_GROUP_ID: null,
				LIKE_CNT: "0",
				WEEKLY_TITLE_IMAGE:
					"https://image.neoflat.net/TB4wpz44lH0jB-gk5rXimEVEJEg=/1376x/filters:no_upscale()/community/5058/59d2253a-d78e-4ec8-b32c-5fe514afd6d8.jpg",
				RECEIPT_FROM_DT: "2024-01-22 00:00:00.0",
				TARGET_DIRECT_IMAGE_URL: null,
				REG_USER_ID: "89278",
				CATEGORY_NM: "#PICK",
				REG_DT: "2024-01-17 16:07:13.0",
				RANDOM: "0.41575291698402994",
				TITLE_IMAGE:
					"https://image.neoflat.net/nJYa6RZ3Cr47eRLwHWvqlqLctsk=/328x328/filters:no_upscale()/community/5058/59d2253a-d78e-4ec8-b32c-5fe514afd6d8.jpg",
				TARGET_IMAGE_URL: null,
				POPULAR_POINT: "10",
				CONTENT_ID: "20811",
				TAG_NAME: null,
				MOD_USER_NO: "89278",
				TARGET_ID: null,
				TYPE_CD: "CATEC00002",
				REG_USER_NO: "89278",
				REG_SEC: "1705475233",
				TARGET_TYPE_CD: null,
				TITLE: "🏢 총 392호 모집 임박! 'LH 수원 행복주택' 꼭 확인하세요! (신청 : 24.01.22~01.24)",
				ZZIM_CNT: "0",
				TARGET_TITLE: null,
				ZZIM_YN: "N",
			},
			{
				TARGET: "RENTAL_HOUST",
				USER_IMAGE:
					"https://image.neoflat.net/nWV0oW9PMb22ZcFQ-EGPD3dEHFU=/72x72/filters:no_upscale()/user/47473/35450a0b-2bde-42a7-90e4-d176b96f7db8",
				COMMENT_CNT: "0",
				ROWNUM: "465",
				REG_USER_TYPE: "10",
				OTHER_COMMENT_CNT: "0",
				LIKE_YN: "N",
				TYPE_NM: "#PICK",
				COMMENT_YN: "N",
				ID: "5055",
				WEIGHT: null,
				DISPLAY_TYPE: "01",
				RECEIPT_TO_DT: null,
				CONTENT_TEXT:
					"안 오르는 것이 없는 고물가 시대.\n그중 가장 부담인 것은 누가 뭐라해도 ‘월세’일 거예요.\n \n특히, 최근 전세사기 여파로 월세 수요가 늘면서, 이는 더욱 심해졌는데요.\n그런데 이런 ‘월세’를 나라로부터 돌려받는 방법이 있다는 것 알고 계셨나요?\n \n바로 ‘월세세액공제’에요.\n \n월세세액공제는 원룸, 오피스텔 뿐만 아니라, 고시원, 쉐어하우스 등에 살고 있어서 신청할 수 있는데요. 특히 올해는 작년보다 조건도 더욱 완화되어 많은 사람들이 혜택을 볼 것으로 예상돼요.\n그럼 지금부터 월세세액공제가 어떤 것인지 함께 알아볼까요?\n \n \n \n’세액공제’는 쉽게 말해, 내야하는 세금 자체를 깎아주는 행위에요. 이중 ‘월세세액공제’는 월세로 1년간 낸 돈을 일정비율 만큼을 세금에서 제외해주는 제도인데요.\n \n23년 정부는 세입자의 주거비 부담 완화를 위해, 이러한 월세세액공제 기준을 완화했는데요.\n이에 따라 올해는 월세세액공제를 통해 연말정산 시 환급받을 수 있는 금액 및 혜택을 받는 사람들이 많아질 것으로 예상돼요.\n \n\n \n \n \n단, 월세를 산다고 해서 누구나 월세세액공제를 받을 수 있는 건 아닌데요. 월세세액공제를 받기 위해선 아래 조건을 모두 만족해여 해요.\n총 급여액 7,000만원 이하 무주택 세대주일 것\n\n단, 종합소득금액(이자, 투자소득 등)이 6,000만원을 초과하지 않아야 해요.\n국민주택(전용 85㎡ 이하) 또는 4억원 이하 주택에 거주 중인 사람일 것\n아파트, 단독 · 다가구, 다세대, 연립주택, 주거용 어피스텔, 원룸, 고시원 등에 거주자일 것\n\n주의사항\n \n또한 이런 ‘월세세액공제’는 최대 연 750까지만 제공되는데요.\n \n특히 총급여 및 종합소득 기준에 따라 최종 공제금액이 달라져요. 월세세액공제의 총급여 및 종합소득에 따른 공제율은 다음과 같아요.\n \n \n \n월세세액공제는 연말정산할 때 함께 신청하면 되는데요.\n \n하지만 홈텍스에서 간소화해서 제출할 수 있는 다른 공제들과는 달리, 회사에 별도의 서류를 제출해야 해요. 제출 시 필요한 서류는 다음과 같습니다.\n월세세액공제는 집주인 동의 없이도 월세 임대차계약서, 월세 납입증명만으로 신청이 가능한대요. 다만, 임대차계약서상 주소지와 주민등록상 주소지가 동일해야하며, 연말정산 신청인과 월세 납부자도 동일해야 하니 꼭 주의해주세요.\n \n \n \n지금까지 월세세액공제에 대해 알아봤는데요. 세액공제가 있듯이, 주택 관련 ‘소득공제’도 있어요. 그중 가장 대표적인 것 3가지를 꼽으면 다음과 같은데요.\n위의 조건에 해당하는 사람이라면, 월세세액공제와 더불어 해당 소득공제도 꼭 받으시길 추천드립니다.\n \n \n이상으로 월세세액공제에 대해서 알아봤어요. 그런데 \"혹시 지금 껏 월세에 살았지만, '월세세액공제'는 한 번도 안했어🥲\" 하시는 분 있으신가요? \n \n그렇다면 아래 링크를 눌러, 고방 월세환급 대상자인지 확인해보세요! \n대상자가 맞다면, 최대 450만원까지 최근 5년간 놓쳤던 월세세액공제 금액을 돌려 받을 수 있어요.\n \n \n\n",
				WEEKLY_TITLE_IMAGE2:
					"https://image.neoflat.net/JQojq-jUNQy-Kb6tpdV8ujzComE=/1376x220/filters:no_upscale()/community/5055/6dd0ebb1-a6b0-4382-ae7c-53ca90c1dc12.jpg",
				BLIND_NOTI_CLUSTER_ID: null,
				VIEW_CNT: "84",
				NICKNAME: "지킴이",
				TITLE_IMAGE4:
					"https://image.neoflat.net/iWTjWZiDEHTzF28LZ89FcVrMcts=/720x540/filters:no_upscale()/community/5055/6dd0ebb1-a6b0-4382-ae7c-53ca90c1dc12.jpg",
				CATEGORY_CD: "C201",
				TAGS: "1인NEWS 혼잘혜택 1인가구지원정책",
				TARGET_STATUS: null,
				MOD_USER_TYPE: "10",
				AUTHOR_YN: "Y",
				TITLE_IMAGE3:
					"https://image.neoflat.net/tfhJVVlNGwvA9vy-Xb5nzWD4mGI=/720x328/filters:no_upscale()/community/5055/6dd0ebb1-a6b0-4382-ae7c-53ca90c1dc12.jpg",
				TITLE_IMAGE2:
					"https://image.neoflat.net/h7SZ8ZY79wScALaM529SRanndC0=/316x260/filters:no_upscale()/community/5055/6dd0ebb1-a6b0-4382-ae7c-53ca90c1dc12.jpg",
				TAG_GROUP_ID: null,
				LIKE_CNT: "0",
				WEEKLY_TITLE_IMAGE:
					"https://image.neoflat.net/6IpRfu2lP1NHj395nuFlogundx8=/1376x/filters:no_upscale()/community/5055/6dd0ebb1-a6b0-4382-ae7c-53ca90c1dc12.jpg",
				RECEIPT_FROM_DT: null,
				TARGET_DIRECT_IMAGE_URL: null,
				REG_USER_ID: "47473",
				CATEGORY_NM: "#PICK",
				REG_DT: "2024-01-16 20:31:51.0",
				RANDOM: "0.881184373871595",
				TITLE_IMAGE:
					"https://image.neoflat.net/qIgPcnUHjJDUPL7c6aa8T3OtIV4=/328x328/filters:no_upscale()/community/5055/6dd0ebb1-a6b0-4382-ae7c-53ca90c1dc12.jpg",
				TARGET_IMAGE_URL: null,
				POPULAR_POINT: "144",
				CONTENT_ID: "20805",
				TAG_NAME: null,
				MOD_USER_NO: "47473",
				TARGET_ID: null,
				TYPE_CD: "CATEC00002",
				REG_USER_NO: "47473",
				REG_SEC: "1705404711",
				TARGET_TYPE_CD: null,
				TITLE: '💵 월세 60만원 냈으면, 122만원 받으세요! "월세세액공제" 간단정리 (고시원, 쉐어하우스도 가능)',
				ZZIM_CNT: "6",
				TARGET_TITLE: null,
				ZZIM_YN: "N",
			},
			{
				TARGET: "RENTAL_HOUST",
				USER_IMAGE:
					"https://image.neoflat.net/90aCCFuf6PEFngYMXc98Y2ethE8=/72x72/filters:no_upscale()/user/2053/b6a7b1cf-ff71-40b1-b350-adee98460556",
				COMMENT_CNT: "0",
				ROWNUM: "464",
				REG_USER_TYPE: "10",
				OTHER_COMMENT_CNT: "0",
				LIKE_YN: "N",
				TYPE_NM: "#PICK",
				COMMENT_YN: "N",
				ID: "5053",
				WEIGHT: null,
				DISPLAY_TYPE: "01",
				RECEIPT_TO_DT: null,
				CONTENT_TEXT:
					"직장인들이 작년 연말정산을 통해 환급받은 평균 금액이 얼마인지 아시나요?\n \n2023년 2월, 직장인들이 돌려받은 연말정산 환급금은 평균 77만 원이라고 하는데요.\n \n작년 연말정산 평균 환급액이 70만 원을 돌파했다는 소식에 올해 돌려받을 ‘연말 정산 환급금’에 대한 기대도 높아지고 있어요.\n \n하지만 연말정산은 복잡한 서류 확인 과정과 매년 달라지는 공제 기준에 사회 초년생에겐 어렵게 다가오는데요.\n \n‘연말정산’이라는 단어만 들어도 막막한 청년들에게 단 1원도 놓치지 않고 환급받을 수 있는 연말 정산 방법에 대해 쉽게 알려드릴게요.\n \n \n \n직장인들이 월급을 받을 때 세금을 제외한 ‘세후’ 금액을 받고 있는 것, 알고 계시죠?\n \n이때 부과되는 세금은 ‘이 정도 금액을 버는 사람이라면, 이 정도 소비를 할 것’이라고 예측하여 매기는 세금이에요.\n \n하지만 같은 금액을 받는 직장인이라도 본인이 살고있는 집이 월세인지 자가인지, 부양가족이 있는지에 따라 소비 금액이 천차만별이죠.\n \n그래서 연말 정산을 통해 실제 소비와 예측된 소비의 차이를 계산하여 세금을 더 받아야 할 사람은 환급금을 받는 것이에요.\n \n \n \n연말 정산을 통해 내가 환급받을 수 있는 금액은 ‘소득공제’와 ‘세액 공제’ 기준에 따라 변경되는데요. 해당 기준은 매년 달라지기 때문에 꼼꼼하게 확인해야 해요.\n \n2023년에도 여러 항목에 대한 공제 기준이 바뀌었는데요. 작년과 달라진 2024년 소득·세액 공제 기준 중 대표적인 항목 다섯 가지에 대해 알려드릴게요.\n \n \n \n앞서 말한 변경 사항만 봐도 연말정산 시 확인해야 할 항목이 정말 많은 것을 알 수 있어요. 직장인들도 매년 복잡한 연말정산 항목들에 불편함을 호소하고 있는데요.\n \n이 불편함을 해소하기 위해 국세청은 지난 15일, 영수증 발급기관이 제출한 의료비, 보험료 등을 바탕으로 소득·세액공제 관련 41개의 자료를 근로자에게 제공하는 ‘연말정산 간소화’ 서비스를 오픈했어요.\n \n해당 서비스의 이용 방법은 다음과 같아요.\n \n홈텍스 접속 후 [연말정산 간소화] 클릭\n\n금융·공인인증서 또는 간편인증을 통해 로그인\n\n적용 월 선택 후 공제 항목을 선택하여 내용 확인\n \n \n연말정산 간소화 서비스가 개통되며 청년들은 의료비, 보험료 등 소득공제 및 세액 공제 자료를 손쉽게 확인할 수 있어요.\n \n하지만 연말정산 간소화 서비스만 믿고 연말정산을 진행했다간 환급금을 모두 돌려받지 못할 수도 있는데요.\n \n연말정산 간소화 서비스는 영수증 발급 기관이 국세청에 제출한 자료를 기반으로 세액공제 자료를 보여주기 때문에 국세청에 제출되지 않은 일부 의료비, 교육비, 기부금, 월세액에 대해선 확인할 수 없기 때문이에요.\n \n서비스에서 확인되지 않는 자료들은 별도로 준비하여 2월 28일까지 회사 또는 세무사를 통해 제출해야 하는데요.\n \n내가 연말정산 간소화 서비스에 나오지 않는 추가적인 공제를 받을 수 있는지 궁금하다면 아래 내용을 통해 학인해 보는 것을 추천드려요.\n \n연말정산 간소화에서 놓치기 쉬운 항목\n \n \n오늘은 13월의 월급이라고 불리는 ‘연말정산’에 대해서 알아봤는데요.\n \n연말 정산 자료를 꼼꼼하게 준비하여 청년들이 받을 수 있는 환급금을 놓치지 않고 모두 돌려받을 수 있길 바라요.\n \n추가로 궁금한 내용이 있다면 ‘국세청 홈택스’ 홈페이지 또는 ‘국세상담센터 (📞126)’을 확인해 주세요!\n \n\n",
				WEEKLY_TITLE_IMAGE2:
					"https://image.neoflat.net/zfpbh5zUUikPNlp7IXAhKJ_JoZM=/1376x220/filters:no_upscale()/community/5053/6a9cc802-a0db-4404-807f-1b4a3e9a2f2e.jpg",
				BLIND_NOTI_CLUSTER_ID: null,
				VIEW_CNT: "60",
				NICKNAME: "안심이",
				TITLE_IMAGE4:
					"https://image.neoflat.net/SiAb6nJqci9UsHcLD6Wi0B4QTrc=/720x540/filters:no_upscale()/community/5053/6a9cc802-a0db-4404-807f-1b4a3e9a2f2e.jpg",
				CATEGORY_CD: "C201",
				TAGS: "1인NEWS 1인가구정보 혼잘트렌드",
				TARGET_STATUS: null,
				MOD_USER_TYPE: "10",
				AUTHOR_YN: "Y",
				TITLE_IMAGE3:
					"https://image.neoflat.net/-h-O-NOZ3RcIYg_yUY8PqLzldgE=/720x328/filters:no_upscale()/community/5053/6a9cc802-a0db-4404-807f-1b4a3e9a2f2e.jpg",
				TITLE_IMAGE2:
					"https://image.neoflat.net/xlcIC_RFBQQv8jF2rvihgkb3YOk=/316x260/filters:no_upscale()/community/5053/6a9cc802-a0db-4404-807f-1b4a3e9a2f2e.jpg",
				TAG_GROUP_ID: null,
				LIKE_CNT: "0",
				WEEKLY_TITLE_IMAGE:
					"https://image.neoflat.net/P4SLxP7FyRnGdVfn19ZstwO-ZNI=/1376x/filters:no_upscale()/community/5053/6a9cc802-a0db-4404-807f-1b4a3e9a2f2e.jpg",
				RECEIPT_FROM_DT: null,
				TARGET_DIRECT_IMAGE_URL: null,
				REG_USER_ID: "2053",
				CATEGORY_NM: "#PICK",
				REG_DT: "2024-01-16 16:29:15.0",
				RANDOM: "0.9967229943691966",
				TITLE_IMAGE:
					"https://image.neoflat.net/q4soIywJrPWAnc4HAcGa7EAdaQ0=/328x328/filters:no_upscale()/community/5053/6a9cc802-a0db-4404-807f-1b4a3e9a2f2e.jpg",
				TARGET_IMAGE_URL: null,
				POPULAR_POINT: "90",
				CONTENT_ID: "20802",
				TAG_NAME: null,
				MOD_USER_NO: "2053",
				TARGET_ID: null,
				TYPE_CD: "CATEC00002",
				REG_USER_NO: "2053",
				REG_SEC: "1705390155",
				TARGET_TYPE_CD: null,
				TITLE: "🚨'연말정산 간소화'만 믿는다면 연말정산 환급금 100% 못받습니다. ",
				ZZIM_CNT: "3",
				TARGET_TITLE: null,
				ZZIM_YN: "N",
			},
			{
				TARGET: "RENTAL_HOUST",
				USER_IMAGE:
					"https://image.neoflat.net/90aCCFuf6PEFngYMXc98Y2ethE8=/72x72/filters:no_upscale()/user/2053/b6a7b1cf-ff71-40b1-b350-adee98460556",
				COMMENT_CNT: "0",
				ROWNUM: "463",
				REG_USER_TYPE: "10",
				OTHER_COMMENT_CNT: "0",
				LIKE_YN: "N",
				TYPE_NM: "#PICK",
				COMMENT_YN: "N",
				ID: "5036",
				WEIGHT: null,
				DISPLAY_TYPE: "01",
				RECEIPT_TO_DT: null,
				CONTENT_TEXT:
					"작년 12월, LH 임대주택 지하 주차장에 주차된 9천만원대의 BMW 차량 사진이 인터넷에서 화제가 된 적이 있었어요.\n \n해당 사진이 화제가 된 이유는 공공임대주택의 입주 조건 중 하나가 본인이 소유한 차량의 자동차 가액이 3,683만 원을 넘어선 안 된다는 조건이기 때문인데요.\n \n사진이 화제가 된 이후 LH와 SH는 고가 차량의 보유 및 주차를 막기 위해 ‘공공주택 업무처리 지침’을 개정했어요.\n \n해당 내용에 대해 자세히 알려드릴게요.\n \n \n \nLH와 SH에서 운영하는 공공임대 주택은 무주택 저소득층의 주거 안정을 목적으로 공급되는 주택이에요.\n \n따라서 공공임대주택에 입주하기 위해선 소득 및 자산 기준을 충족해야 하죠.\n \n2023년, 공공임대주택 입주를 위한 자동차 기준 가액은 3,683만 원 이하였는데요.\n \n이러한 제도가 무색하게 공공임대주택 주차장에서 온갖 고급 자동차가 주차되어 있다는 이야기가 나오자 크게 이슈가 된 것이에요.\n \n \n \n해당 사진을 확인하고 문제를 인지한 LH는 전국 임대 단지에 ‘고가 차량의 보유 및 주차를 제한한다’는 공지를 냈어요.\n \n공지에는 자동차가액 3,683만 원 이하의 자동차만 주차 등록을 할 수 있다는 내용과 함께 고가로 추정되는 차량은 관리사무소에서 직접 연락을 취하겠다는 내용이 포함되어 있었죠.\n \n이후 SH 공사에서 공공임대주택단지 내 차량 등록 현황을 조사했는데요. 조사 결과, 총 337대가 기준 가액을 초과했다고 해요.\n \n해당 문제를 해결하기 위해 SH는 국토교통부에 공공주택 업무처리 지침 개정을 요청했어요.\n \n \n \nSH의 요청에 따라 지난 5일, ‘공공주택 특별법 시행 규칙’이 개정되었는데요. 개정된 내용은 다음과 같아요.\n \n \n \n \n지하 주차장에 주차된 BMW 차량 사진이 업로드된 지 두 달 만에 공공주택 특별법까지 개정되었는데요.\n \n이 사진 한 장에 많은 사람들이 분노한 이유에는 공공임대주택이 매년 사악한 경쟁률을 보인 탓도 있을 거예요.\n \n공공임대 주택은 ‘무주택자의 내집마련을 돕기 위한 제도’인데요. 국토교통부가 발표한 ‘2022년 주거 실태 조사’에 따르면 대한민국 국민의 42.5%가 ‘무주택자’라고 해요.\n \n전체 국민의 10명 중 4명이 ‘무주택자’이기 때문에 공공임대주택은 매 공고마다 높은 경쟁률을 보일 수밖에 없고, 그 경쟁률을 뚫고 입주한 입주민이 사실 1억원대 차량을 소유한 ‘가짜 서민’이라는 사실에 많은 국민들이 분노한 것이죠.\n \n오늘은 지난 5일 변경된 ‘공공주택 특별법 시행 규칙’에 대해서 알아봤는데요.\n \n무주택자가 42.5%인 사회에서 '무주택자의 내집마련'을 목적으로 한 공공임대주택이 원활하게 운영되기 위해선 공급 질서를 더욱 꼼꼼히 확립할 필요성이 대두되고 있어요. \n \n공공임대주택을 포함한 수많은 정책이 정책을 필요로 하는 사람들에게 돌아갈 수 있도록 돕는 장치가 하루빨리 마련되길 바랍니다.\n \n\n",
				WEEKLY_TITLE_IMAGE2:
					"https://image.neoflat.net/cSXXGowlY44_7M2v_qCwBkWsTxo=/1376x220/filters:no_upscale()/community/5036/b363c7d4-1ab7-4f6d-8699-da8d87f6d90f.jpg",
				BLIND_NOTI_CLUSTER_ID: null,
				VIEW_CNT: "104",
				NICKNAME: "안심이",
				TITLE_IMAGE4:
					"https://image.neoflat.net/o4_T6C1_NToRmk8YGlwbi5hDkt0=/720x540/filters:no_upscale()/community/5036/b363c7d4-1ab7-4f6d-8699-da8d87f6d90f.jpg",
				CATEGORY_CD: "C201",
				TAGS: "1인NEWS 1인가구정보 혼잘주거",
				TARGET_STATUS: null,
				MOD_USER_TYPE: "20",
				AUTHOR_YN: "Y",
				TITLE_IMAGE3:
					"https://image.neoflat.net/hUyn32UaYluSmZA25tu5kqsZ7WY=/720x328/filters:no_upscale()/community/5036/b363c7d4-1ab7-4f6d-8699-da8d87f6d90f.jpg",
				TITLE_IMAGE2:
					"https://image.neoflat.net/F7d2kBKRH44y6Tv4zke8wvYsGqo=/316x260/filters:no_upscale()/community/5036/b363c7d4-1ab7-4f6d-8699-da8d87f6d90f.jpg",
				TAG_GROUP_ID: null,
				LIKE_CNT: "0",
				WEEKLY_TITLE_IMAGE:
					"https://image.neoflat.net/J-frNdAryrJtqls52u2ST7-zwNM=/1376x/filters:no_upscale()/community/5036/b363c7d4-1ab7-4f6d-8699-da8d87f6d90f.jpg",
				RECEIPT_FROM_DT: null,
				TARGET_DIRECT_IMAGE_URL: null,
				REG_USER_ID: "2053",
				CATEGORY_NM: "#PICK",
				REG_DT: "2024-01-11 14:46:11.0",
				RANDOM: "0.7008102095693445",
				TITLE_IMAGE:
					"https://image.neoflat.net/g3pk3hPO4j2HXGG1vL-iHQFcdew=/328x328/filters:no_upscale()/community/5036/b363c7d4-1ab7-4f6d-8699-da8d87f6d90f.jpg",
				TARGET_IMAGE_URL: null,
				POPULAR_POINT: "124",
				CONTENT_ID: "20733",
				TAG_NAME: null,
				MOD_USER_NO: "2506",
				TARGET_ID: null,
				TYPE_CD: "CATEC00002",
				REG_USER_NO: "2053",
				REG_SEC: "1704951971",
				TARGET_TYPE_CD: null,
				TITLE: "🚗 LH·SH 공공임대주택 자동차 가액 기준 변경! 이제 ‘꼼수’ 안 통합니다. ",
				ZZIM_CNT: "2",
				TARGET_TITLE: null,
				ZZIM_YN: "N",
			},
			{
				TARGET: "RENTAL_HOUST",
				USER_IMAGE:
					"https://image.neoflat.net/90aCCFuf6PEFngYMXc98Y2ethE8=/72x72/filters:no_upscale()/user/2053/b6a7b1cf-ff71-40b1-b350-adee98460556",
				COMMENT_CNT: "0",
				ROWNUM: "462",
				REG_USER_TYPE: "10",
				OTHER_COMMENT_CNT: "0",
				LIKE_YN: "N",
				TYPE_NM: "#PICK",
				COMMENT_YN: "N",
				ID: "5035",
				WEIGHT: null,
				DISPLAY_TYPE: "01",
				RECEIPT_TO_DT: null,
				CONTENT_TEXT:
					"매년 12월에서 2월은 부동산 계약이 가장 많이 일어나는 ‘부동산 성수기’예요.\n \n이 시기에는 학업이나 취업을 이유로 생애 첫 자취방을 계약하는 청년들도 많은데요. 처음 자취방을 구할 땐 뭐부터 해야 할지 막막할 거예요.\n \n그래서 고방이 예비 자취생들을 위해 자취방을 구할 때 필요한 정보를 매주 하나씩 소개하기로 했어요.\n \n오늘은 자취방을 구할 때 가장 먼저 확인해야 할 '자취방 유형'에 대해 소개해 드릴게요.\n \n \n \n대부분 '자취'라고 하면 원룸을 떠올릴 거예요.\n \n물론 많은 사람들이 원룸에서 자취 생활을 하고 있지만, 그렇다고 해서 모든 자취생들이 원룸에서 생활하는 것은 아니에요. 원룸은 수많은 자취방 유형 중 하나일 뿐이죠.\n \n1인가구가 증가함에 따라 우리 사회에는 1인 가구의 특성을 반영한 다양한 주거 유형이 생겨났는데요. 이러한 주거 유형들은 월세, 보증금, 계약기간 등에서 차이를 보이며 1인가구 자취생들의 주거 선택지를 넓히고 있어요.\n \n그동안 자취 공간으로 ‘원룸’만 고려하고 있었다면 이 글을 통해 자취방의 선택지를 확장해 보세요.\n \n \n \n원룸은 방 하나에 침실, 거실, 부엌 등 모든 기능이 포함된 주거 공간을 말해요. 대학생들 사이 가장 일반적인 자취 유형이죠.\n \n \n1. 독립적인 생활: 원룸은 생활 공간 전부를 나 혼자 사용하기 때문에 식사, 청소, 지인 초대, 통금 시간으로부터 자유로워요.\n \n비싼 월세와 보증금: 원룸은 다른 주거 유형에 비해 보증금과 월세가 높아요. 2023년 자료에 따르면 서울 대학가 자취방의 평균 월세가 69만 원이라고 하죠.\n높은 초기 비용: 원룸의 경우 침대·책상·의자·수납장·전신거울·주방용품과 같은 생활 가구를 내가 따로 구입해야 하기 때문에 자취 초기 발생하는 가구 및 생필품 구입 비용이 많이 들어요.\n \n \n \n \n쉐어하우스는 아파트와 같이 면적이 넓은 집을 다수가 함께 사용하는 주거 공간이에요.\n \n침실 등 개인 공간은 독립적으로 사용하면서, 주방·거실 등 공용공간은 입주자들이 함께 사용하는 주거 유형이죠.\n \n \n \n \n \n \n \n \n고시원은 장기 수험생들이 공부에 집중할 수 있도록 침대, 책상 등 최소한의 시설로만 구성된 좁은 방을 말했어요.\n \n하지만 현재는 넓은 방에 최신 가구를 배치한 프리미엄 고시텔과 원룸텔이 등장하며 점차 그 의미가 변화하고 있죠.\n \n \n \n \n \n \n \n오늘은 대표적인 자취 유형인 원룸, 쉐어하우스, 고시원에 대해 알아봤는데요.\n \n자신만의 라이프 스타일을 가진 1인가구가 증가함에 따라 1인가구의 니즈를 반영한 다양한 주거 공간이 나오고 있어요.\n \n고방 또한 1인가구 청년들이 자신의 성향에 맞는 공간을 쉽게 확인할 수 있도록 주차 공간, 엘리베이터, 카드 결제, 다인실 여부 등을 확인 할 수 있는 필터 기능을 제공 중이니 집을 구할 때 활용해 보세요!\n \n\n \n \n청년들이 기존의 정형화된 선택지에서 벗어나 나의 생활 패턴에 맞는 주거 공간을 선택할 수 있길 바랍니다.\n \n\n",
				WEEKLY_TITLE_IMAGE2:
					"https://image.neoflat.net/srZ6rpdM8gSLS1ivYIWEfYS0L_E=/1376x220/filters:no_upscale()/community/5035/99943586-6952-48fc-9ddb-ef6fe45e7a46.jpg",
				BLIND_NOTI_CLUSTER_ID: null,
				VIEW_CNT: "347",
				NICKNAME: "안심이",
				TITLE_IMAGE4:
					"https://image.neoflat.net/CdGkIBzxko5bWk3Pt7Wi7BWa4U4=/720x540/filters:no_upscale()/community/5035/99943586-6952-48fc-9ddb-ef6fe45e7a46.jpg",
				CATEGORY_CD: "C201",
				TAGS: "1인NEWS 1인가구문화 시리즈픽 청년주거 혼잘주거",
				TARGET_STATUS: null,
				MOD_USER_TYPE: "20",
				AUTHOR_YN: "Y",
				TITLE_IMAGE3:
					"https://image.neoflat.net/ZKwPiMwnrzmaAxneUe6kknixdO4=/720x328/filters:no_upscale()/community/5035/99943586-6952-48fc-9ddb-ef6fe45e7a46.jpg",
				TITLE_IMAGE2:
					"https://image.neoflat.net/scpgU0JfW2Z1xrkQwjE0BJ-VYFo=/316x260/filters:no_upscale()/community/5035/99943586-6952-48fc-9ddb-ef6fe45e7a46.jpg",
				TAG_GROUP_ID: null,
				LIKE_CNT: "0",
				WEEKLY_TITLE_IMAGE:
					"https://image.neoflat.net/4X9lAGavnmz_Wyj25PwFSdM3_F8=/1376x/filters:no_upscale()/community/5035/99943586-6952-48fc-9ddb-ef6fe45e7a46.jpg",
				RECEIPT_FROM_DT: null,
				TARGET_DIRECT_IMAGE_URL: null,
				REG_USER_ID: "2053",
				CATEGORY_NM: "#PICK",
				REG_DT: "2024-01-11 10:43:07.0",
				RANDOM: "0.8357760280703902",
				TITLE_IMAGE:
					"https://image.neoflat.net/HNUs3ROfuRURkahigXtAbW8Qgfg=/328x328/filters:no_upscale()/community/5035/99943586-6952-48fc-9ddb-ef6fe45e7a46.jpg",
				TARGET_IMAGE_URL: null,
				POPULAR_POINT: "377",
				CONTENT_ID: "20731",
				TAG_NAME: null,
				MOD_USER_NO: "2506",
				TARGET_ID: null,
				TYPE_CD: "CATEC00002",
				REG_USER_NO: "2053",
				REG_SEC: "1704937387",
				TARGET_TYPE_CD: null,
				TITLE: "자취방 구하기(1) - 자취방 구할 때, 내 선택지가 항상 좁은 이유.  ",
				ZZIM_CNT: "3",
				TARGET_TITLE: null,
				ZZIM_YN: "N",
			},
		],
		RESULT_CD: "SUCC_0001",
	},
];
